#!/usr/bin/env python3
"""
Generate answer-hint reasoning for CWAD training data using Qwen3.5-0.8B.

For each row of the training parquet, feed the world's image + question +
ground-truth answer to the model and ask it to explain why that answer is
correct. Output: JSONL with one record per sample containing the original data +
reasoning.

Every path comes from the environment, because this is the one step that runs
wherever a card happens to be free:

    HINT_PARQUET=/data/dual_world.parquet \
    HINT_MODEL=/models/Qwen3.5-0.8B \
    HINT_OUTPUT_DIR=/data/hints \
    HINT_QC_LIST=/data/qc_score_passed.jsonl \   # world B only
    HINT_WORLD=a HINT_SHARD=0/2 \
    python scripts/generate_answer_hints.py

HINT_SHARD=k/n splits the rows over n processes; each shard writes its own file
and merge_answer_hints.py concatenates them.
"""
import json, re, time, os, sys
from pathlib import Path
from PIL import Image
import torch
import pandas as pd
from transformers import AutoProcessor, Qwen3_5ForConditionalGeneration

def require_env(name):
    value = os.environ.get(name, "").strip()
    if not value:
        raise SystemExit(f"{name} is required; every path is passed through the environment")
    return value


# The dual-world parquet whose rows get hints: HINT_PARQUET.
PARQUET = require_env("HINT_PARQUET")
# Which checkpoint writes the hints: the 0.8B chain is often thinner than the
# answer deserves, and a 4B teacher is a legitimate choice, so there is no default.
MODEL   = require_env("HINT_MODEL")

# Which world to write hints for. Each world has its own image and its own correct
# answer, so the two passes are the same job over different columns:
#   world a -- the original image, whose answer is the dataset's ground truth
#   world b -- the counterfactual edit, whose answer is the option the edit made
#              true (chosen_option in the QC list); the ground truth is false there
WORLD = os.environ.get("HINT_WORLD", "a").lower()
if WORLD not in {"a", "b"}:
    raise SystemExit(f"HINT_WORLD must be 'a' or 'b', got {WORLD!r}")

_BASE = require_env("HINT_OUTPUT_DIR")
IMAGE_KEY = "images" if WORLD == "a" else "teacher_images"
# Sharding: HINT_SHARD=k/n splits the row set across n processes so several GPUs
# can generate at once. Each shard keeps its own output file -- concurrent appends
# to one file over NFS are not atomic -- and the caller concatenates them after.
_SHARD = os.environ.get("HINT_SHARD", "0/1")
_shard_k, _shard_n = (int(v) for v in _SHARD.split("/"))
assert 0 <= _shard_k < _shard_n, f"bad HINT_SHARD {_SHARD!r}"
SHARD_K, SHARD_N = _shard_k, _shard_n

# Suffix distinguishes hint sets generated by different models, e.g. "_4b", so a
# stronger model's output lands beside the 0.8B one instead of overwriting it.
SUFFIX = os.environ.get("HINT_SUFFIX", "")
_world_file = f"answer_hints_{WORLD}{SUFFIX}.jsonl"
OUTPUT = os.path.join(
    _BASE, _world_file if SHARD_N == 1 else _world_file.replace(".jsonl", f"_s{SHARD_K}.jsonl")
)
# Rows produced by earlier or unsharded passes: every shard treats them as done so
# nothing is generated twice. The pool file is shared across a world's shards.
LEGACY_OUTPUT = os.environ.get(
    "HINT_DONE_POOL", os.path.join(_BASE, f"answer_hints_{WORLD}{SUFFIX}_done.jsonl")
)
LOG = os.path.join(_BASE, f"answer_hints{WORLD}_s{SHARD_K}.log")
# Only the world-B pass needs it: it maps a parquet row ordinal to the option the
# edit made true.
QC_LIST = require_env("HINT_QC_LIST") if WORLD == "b" else ""

# Both are overridable so a run can be sized to the card it lands on: the 0.8B
# model leaves most of a 24 GB card idle at batch 8, and generation is dominated
# by how many sequences are in flight, not by how long each one is.
BATCH_SIZE  = int(os.environ.get("HINT_BATCH_SIZE", "8"))
MAX_TOKENS  = int(os.environ.get("HINT_MAX_TOKENS", "512"))
MAX_PIXELS  = 1048576   # 1024x1024

REASONING_PROMPT = (
    "Look at the image carefully and answer the question. "
    "The correct answer is **{answer}**. "
    "Explain step by step why this is the correct answer, "
    "referring to specific visual details in the image.\n\n{question}"
)


def log(msg):
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(LOG, "a") as f:
        f.write(line + "\n")


def load_data():
    df = pd.read_parquet(PARQUET)
    log(f"Loaded {len(df)} rows from {PARQUET}")
    return df


def load_done_indices():
    done = set()
    for path in (OUTPUT, LEGACY_OUTPUT):
        if not os.path.exists(path):
            continue
        with open(path) as f:
            for line in f:
                try:
                    done.add(json.loads(line)["idx"])
                except Exception:
                    pass
    return done


def load_chosen_options():
    """parquet row ordinal -> chosen_option, for the world-B pass.

    The edit was generated so that one specific wrong option becomes true; that
    option, not the dataset ground truth, is the answer the world-B image shows.

    Keyed by the QC list's `idx`, which is the row ordinal in the *unfiltered*
    parquet -- the list holds only the QC-passed rows, so those indices are
    sparse (0, 21, ...) and are NOT the dual-world parquet's row ordinals.
    """
    options = {}
    with open(QC_LIST) as handle:
        for line in handle:
            if not line.strip():
                continue
            record = json.loads(line)
            options[int(record["idx"])] = record["chosen_option"]
    return options


CHOSEN_OPTIONS = load_chosen_options() if WORLD == "b" else {}
_EDIT_NAME = re.compile(r"idx(\d+)_edited")

def answer_for(row, idx):
    """The answer this world's image actually shows.

    World A is the untouched original, so the dataset ground truth is correct.
    World B is the counterfactual edit, so the answer is the option the edit made
    true. That option is looked up by the parquet row ordinal carried in the edit
    filename, which is the one identifier the two index spaces agree on.
    """
    if WORLD == "b":
        match = _EDIT_NAME.search(row[IMAGE_KEY][0]["image"])
        if match is None:
            raise ValueError(f"cannot read a parquet row ordinal from {row[IMAGE_KEY][0]['image']!r}")
        option = CHOSEN_OPTIONS.get(int(match.group(1)))
        if option is None:
            raise KeyError(f"no chosen_option for parquet row {match.group(1)} in {QC_LIST}")
        return option
    return row["reward_model"]["ground_truth"]


def build_reasoning_text(row, idx):
    prompt_msgs = row["prompt"]
    question_text = ""
    for msg in prompt_msgs:
        content = msg.get("content", "")
        content = content.replace("<image>", "").strip()
        if content:
            question_text = content
            break

    answer = answer_for(row, idx)
    return REASONING_PROMPT.format(answer=answer, question=question_text), answer


_THINK_BLOCK = re.compile(r"<think>.*?</think>", re.DOTALL)
_MIN_REASONING_CHARS = 100


def clean_reasoning(text: str) -> str:
    """Strip chat-template residue from a generated hint, and reject junk.

    The model sometimes re-emits the assistant header or opens a thinking block,
    and a hint that is one character long (a right-padding artifact, or an
    immediate EOS) is worse than no hint at all -- it would teach the teacher
    nothing while still burning prompt length. Anything that cleans down to
    fewer than _MIN_REASONING_CHARS characters is reported as an error so the
    row is retried rather than silently kept.
    """
    cleaned = _THINK_BLOCK.sub("", text.strip())
    cleaned = cleaned.strip()
    # Drop a leading assistant/template marker the model echoed back.
    cleaned = re.sub(r"^(assistant\s*)+", "", cleaned).strip()
    if len(cleaned) < _MIN_REASONING_CHARS:
        return f"[ERR:too-short:{len(cleaned)}]"
    return cleaned


def resize_image(img, max_pixels=MAX_PIXELS):
    w, h = img.size
    if w * h <= max_pixels:
        return img
    scale = (max_pixels / (w * h)) ** 0.5
    new_w, new_h = int(w * scale), int(h * scale)
    return img.resize((new_w, new_h), Image.Resampling.LANCZOS)


def load_image(row):
    img_path = row[IMAGE_KEY][0]["image"]
    try:
        img = Image.open(img_path).convert("RGB")
        return resize_image(img)
    except Exception as e:
        log(f"  [WARN] Cannot load {img_path}: {e}")
        return None


def main():
    df = load_data()
    done = load_done_indices()
    todo_indices = [
        i for i in range(len(df)) if i not in done and i % SHARD_N == SHARD_K
    ]
    log(f"shard {SHARD_K}/{SHARD_N}: already done {len(done)}, remaining {len(todo_indices)}")

    if not todo_indices:
        log("Nothing to do.")
        return

    log(f"Loading model from {MODEL} ...")
    processor = AutoProcessor.from_pretrained(MODEL, trust_remote_code=True)
    # Batched decode requires left padding: with right padding the model continues
    # from the pad tokens instead of the prompt, which produced single-character
    # and template-echo outputs for everything shorter than the batch maximum.
    if getattr(processor, "tokenizer", None) is not None:
        processor.tokenizer.padding_side = "left"
    processor.padding_side = "left"
    model = Qwen3_5ForConditionalGeneration.from_pretrained(
        MODEL,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        ignore_mismatched_sizes=True,
        attn_implementation="sdpa",
    )
    model.eval()
    gpu_free = torch.cuda.mem_get_info(0)[0] / 1e9
    log(f"Model loaded. GPU free: {gpu_free:.1f} GB")

    t0 = time.time()
    total = len(todo_indices)

    with open(OUTPUT, "a") as fout:
        for batch_start in range(0, total, BATCH_SIZE):
            batch_idx = todo_indices[batch_start : batch_start + BATCH_SIZE]
            rows = [df.iloc[i] for i in batch_idx]

            texts = []
            images = []
            valid_mask = []

            for row, idx_of_row in zip(rows, batch_idx):
                reasoning_text, gt = build_reasoning_text(row, idx_of_row)
                img = load_image(row)
                if img is not None:
                    texts.append(reasoning_text)
                    images.append(img)
                    valid_mask.append(True)
                else:
                    texts.append(reasoning_text)
                    images.append(None)
                    valid_mask.append(False)

            messages_list = []
            for txt, img in zip(texts, images):
                if img is not None:
                    content = [{"type": "image", "image": img}, {"type": "text", "text": txt}]
                else:
                    content = [{"type": "text", "text": txt}]
                messages_list.append([{"role": "user", "content": content}])

            try:
                applied = [
                    processor.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
                    for msgs in messages_list
                ]
                inputs = processor(
                    text=applied,
                    images=[img for img in images],
                    return_tensors="pt",
                    padding=True,
                    truncation=True,
                ).to(model.device)

                with torch.no_grad():
                    outputs = model.generate(
                        **inputs,
                        max_new_tokens=MAX_TOKENS,
                        temperature=0.6,
                        do_sample=True,
                        top_p=0.95,
                    )

                prompt_lens = inputs["input_ids"].shape[1]
                generated_texts = processor.batch_decode(
                    outputs[:, prompt_lens:], skip_special_tokens=True
                )

                for j, idx in enumerate(batch_idx):
                    row = df.iloc[idx]
                    gt = answer_for(row, idx)
                    reasoning = clean_reasoning(generated_texts[j]) if valid_mask[j] else ""
                    record = {
                        "idx": idx,
                        "ground_truth": gt,
                        "reasoning": reasoning,
                        "image_path": row[IMAGE_KEY][0]["image"],
                        "world": WORLD,
                "model": "Qwen3.5-0.8B",
                    }
                    fout.write(json.dumps(record, ensure_ascii=False) + "\n")

            except Exception as e:
                log(f"  [ERR] batch {batch_start}: {e}")
                for j, idx in enumerate(batch_idx):
                    row = df.iloc[idx]
                    gt = row["reward_model"]["ground_truth"]
                    record = {
                        "idx": idx,
                        "ground_truth": gt,
                        "reasoning": f"[ERR:{str(e)[:200]}]",
                        "image_path": row[IMAGE_KEY][0]["image"],
                        "world": WORLD,
                "model": "Qwen3.5-0.8B",
                    }
                    fout.write(json.dumps(record, ensure_ascii=False) + "\n")

            fout.flush()
            processed = min(batch_start + BATCH_SIZE, total)
            elapsed = time.time() - t0
            speed = processed / max(elapsed, 0.1)
            eta = (total - processed) / max(speed, 0.1)

            if processed % 100 < BATCH_SIZE or processed == total:
                log(f"[{processed}/{total}] {speed:.1f}/s  ETA: {eta:.0f}s")

    elapsed = time.time() - t0
    log(f"DONE: {total} samples in {elapsed/60:.1f} min -> {OUTPUT}")


if __name__ == "__main__":
    main()
